apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-staging
  namespace: argocd
spec:
  project: demo-team
  source:
    repoURL: https://github.com/orenamir2/argocd-demo-gitops.git
    targetRevision: main
    path: charts/argocd-demo
    helm:
      releaseName: argocd-demo
      valueFiles:
        - ../../environments/staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
