replicaCount: 1

image:
  repository: ghcr.io/orenamir2/argocd-demo
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  pullSecrets:
    - ghcr-pull-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  name: ""

ingress:
  enabled: false
  className: nginx
  host: argocd-demo.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

environment: default
