replicaCount: 1

image:
  tag: "1.0.0"

environment: dev

ingress:
  enabled: false
  host: argocd-demo-dev.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
