replicaCount: 3

image:
  tag: "1.0.0"

environment: production

ingress:
  enabled: false
  host: argocd-demo.example.com

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
