apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-demo.fullname" . }}
  labels:
    {{- include "argocd-demo.labels" . | nindent 4 }}
data:
  APP_ENVIRONMENT: {{ .Values.environment | quote }}
