apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-demo.fullname" . }}
  labels:
    {{- include "argocd-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "argocd-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argocd-demo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "argocd-demo.serviceAccountName" . }}
      containers:
        - name: {{ include "argocd-demo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "argocd-demo.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
